# Práctica Clase 3

## Numpy

In [2]:
import numpy as sa

**Ejercicio 1**: Responder las siguientes preguntas:
* ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.
    Ningun tipo de operacion ya que el arreglo numpy es diferente
* ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.
    multiplicacion,divicion,potenciacion 
* ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta.
La diferencia radica en el tipo de arreglo o el tipo de dimension es decir cunatas filas y comnas tiene cada arreglo
(el primero representa el número de filas y el segundo el número de columnas.)


In [3]:
sa.full(shape=(2,4) ,fill_value=sa.pi)


array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [5]:
matrix.shape

<function shape at 0x000001B058404430>

In [6]:
my_list=[1,2,3,4,5,6,6,7]
print(sa.array(my_list))

[1 2 3 4 5 6 6 7]


In [9]:
sa.arange(start=1, stop=12, step=2)

array([ 1,  3,  5,  7,  9, 11])

In [11]:
sa.linspace(start=1 ,stop=11,num=100)

array([ 1.        ,  1.1010101 ,  1.2020202 ,  1.3030303 ,  1.4040404 ,
        1.50505051,  1.60606061,  1.70707071,  1.80808081,  1.90909091,
        2.01010101,  2.11111111,  2.21212121,  2.31313131,  2.41414141,
        2.51515152,  2.61616162,  2.71717172,  2.81818182,  2.91919192,
        3.02020202,  3.12121212,  3.22222222,  3.32323232,  3.42424242,
        3.52525253,  3.62626263,  3.72727273,  3.82828283,  3.92929293,
        4.03030303,  4.13131313,  4.23232323,  4.33333333,  4.43434343,
        4.53535354,  4.63636364,  4.73737374,  4.83838384,  4.93939394,
        5.04040404,  5.14141414,  5.24242424,  5.34343434,  5.44444444,
        5.54545455,  5.64646465,  5.74747475,  5.84848485,  5.94949495,
        6.05050505,  6.15151515,  6.25252525,  6.35353535,  6.45454545,
        6.55555556,  6.65656566,  6.75757576,  6.85858586,  6.95959596,
        7.06060606,  7.16161616,  7.26262626,  7.36363636,  7.46464646,
        7.56565657,  7.66666667,  7.76767677,  7.86868687,  7.96

In [12]:
sa.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
sa.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [14]:
sa.full(shape=(2,4) ,fill_value=2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

In [19]:
matrix=sa.arange(16).reshape(4,4)
print(matrix) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [23]:
print(matrix[0,1])

1


In [24]:
print(matrix[0,2])

2


A partir de una lista podemos crear un arreglo de numpy

In [25]:
lista = [0,1,2,3,4,5]
arreglo = sa.array(lista)
print(lista)
print(arreglo)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


Pero para algunos casos numpy tiene funciones que crean listas más rápidamente.

In [26]:
arreglo = sa.arange(8)
print(arreglo)

[0 1 2 3 4 5 6 7]


Algunas cosas que se pueden hacer con arreglos pero no con las listas:

1. Sumarle un mismo elemento

In [5]:
lista + 1

TypeError: can only concatenate list (not "int") to list

In [6]:
arreglo = arreglo + 1

In [7]:
arreglo

array([1, 2, 3, 4, 5, 6, 7, 8])

2. Elevar al cuadrado todos los elementos

In [8]:
lista**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [9]:
arreglo**2

array([ 1,  4,  9, 16, 25, 36, 49, 64], dtype=int32)

3. Sumar todos los elementos

In [10]:
print(arreglo.sum())
print(lista.sum())

36


AttributeError: 'list' object has no attribute 'sum'

In [27]:
n = 0
for e in lista:
    n = n + e
print(n)

15


In [12]:
arreglo.shape

(6,)

In [47]:
arreglo = sa.array([[1,2,3,4,5,6],[1,2,3,7,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1 2 3 4 5 6]
 [1 2 3 7 5 6]
 [1 2 3 4 5 6]] . Shape = (3, 6) 



In [30]:
arreglo = sa.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1 2 3 4 5 6]] . Shape = (1, 6) 



In [31]:
arreglo = sa.array([[1,2,3,4,5,6]]).T #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 



In [25]:
#¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)?

print('Arreglo de (n,)')
arreglo = sa.array([1,2,3,4,5,6])
print(arreglo,'. Shape =', arreglo.shape, "\n") # "\n" imprime un salto de linea
# para los arreglos numpy, la funcion shape devuelve un tupla que contiene el numero de elemntos a lo largo de cada dimension del arreglo. cabe resaltar que le primer elemento represnta el numero de fias y el sengudo el numero de columnas

print('Arreglo de (2,n)')
arreglo = sa.array([[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

print('Arreglo de (n,1)')
arreglo = sa.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo.T,'. Shape =', arreglo.T.shape, "\n")   #notar .T, que significa transpuesto


Arreglo de (n,)
[1 2 3 4 5 6] . Shape = (6,) 

Arreglo de (2,n)
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]] . Shape = (2, 6) 

Arreglo de (n,1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1)


In [ ]:
### EXTRA 1###
#Trasponer no es la unica forma de crear un arreglo de forma (n,1)'''
arreglo = sa.array([[1],[2],[3],[4],[5],[6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape)   #notar .T, que significa transpuesto

In [43]:
a1 = sa.array([[1,2,3,4],[5,6,7,8]])
a1.shape

(2, 4)

In [44]:
a2 = sa.array([[1,2,3,4],[5,6,7,8]])
a2.shape

(2, 4)

In [45]:
a3 = a1 * a2
a3.shape

(2, 4)

In [46]:
a3

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

**Ejercicio 2**:
* Escribir un arreglo con números enteros del 0 al 9. Pista: arange
* Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace

In [10]:
arr=sa.arange(start= 0,stop=10,step=1)
arr1=sa.linspace(start=0,stop=10,num=100)
print(arr)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]
[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.0

**Ejercicio 3**:
* Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son divisibles por 3<br>
Pista: mask

In [22]:
numeros=sa.array([1,2,1,5,4,5,4,6,5,44,6,584])
for i in numeros:
    if i%3==0:
        print(i)

6
6


**Ejercicio 4**:
* Crear un arreglo de ceros de `shape` (5,10).
* Reemplazar la segunda y cuarta fila con unos
* Reemplazar la tercera y octava columna con dos (2).

In [33]:
arr=sa.zeros((5,10))
a=arr.shape
print(arr)
print(a)
b=arr[3]=1#Este comando se utiliza para remplazar la fila con el valor que nosotros queramos
print(b)
print(arr)
v=arr[:,2]=2#Este comando se utiliza para remplazar la columna 
print(arr)
j=arr[:,7]=2
print(arr)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(5, 10)
1
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 2. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 2. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 2. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]
 [0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]
 [0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]
 [1. 1. 2. 1. 1. 1. 1. 2. 1. 1.]
 [0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]]


**Ejercicio $\infty$**:
Hacer todos los ejercicios que puedan del siguiente link https://www.machinelearningplus.com/python/101-numpy-exercises-python/

O de https://github.com/rougier/numpy-100

Para explorar las funciones de creación de datos aleatorios:
https://numpy.org/doc/stable/reference/random/legacy.html

In [7]:
a = sa.random.random((4,2,3)) * 100 + 100
a

array([[[150.11556388, 197.72798273, 116.18734856],
        [128.31572117, 107.03603989, 160.32237545]],

       [[119.60685446, 180.17727648, 166.12385362],
        [147.35325641, 135.6169305 , 189.83497315]],

       [[115.74732483, 122.15398296, 181.97777115],
        [137.86570148, 107.00807916, 151.6561461 ]],

       [[100.28411858, 173.36548498, 169.6226789 ],
        [143.34071793, 141.38848409, 185.52998166]]])

In [37]:
a = sa.random.random((4,4))

In [38]:
a

array([[0.93500288, 0.14898902, 0.40586314, 0.40639563],
       [0.87948744, 0.49734689, 0.01041626, 0.89861767],
       [0.15963697, 0.41152716, 0.08044375, 0.18127403],
       [0.88021094, 0.17549489, 0.8726642 , 0.8713119 ]])

In [41]:
a = sa.array([[10,200,30,45,5,50],[5,20,30,40,50,0],[5,20,30,40,50,0],[5,20,30,40,50,0]], dtype=sa.int8)

C:\Users\salin\AppData\Local\Temp\ipykernel_5772\3265198313.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 200 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  a = sa.array([[10,200,30,45,5,50],[5,20,30,40,50,0],[5,20,30,40,50,0],[5,20,30,40,50,0]], dtype=sa.int8)


In [42]:
a

array([[ 10, -56,  30,  45,   5,  50],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0]], dtype=int8)

In [43]:
a.sum()

519

In [44]:
a.std()

23.924904214367643

In [45]:
a.sort(axis=1)

In [46]:
a

array([[-56,   5,  10,  30,  45,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50]], dtype=int8)

In [47]:
a.sort(axis=0)
a

array([[-56,   5,  10,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  45,  50]], dtype=int8)

In [48]:
a[1:3,0:3]

array([[ 0,  5, 20],
       [ 0,  5, 20]], dtype=int8)

In [49]:
l =   [[ 10, 200,  30,  45,   5, 100],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0]]

In [28]:
a = np.array([l])

In [31]:
a.shape

(1, 4, 6)

In [32]:
a.reshape(24)

array([ 10, 200,  30,  45,   5, 100,   5,  20,  30,  40,  50,   0,   5,
        20,  30,  40,  50,   0,   5,  20,  30,  40,  50,   0])

In [33]:
a = np.matrix([[1,2,3,4,5,6]]) 
print(a) 

[[1 2 3 4 5 6]]


In [5]:
b = np.matrix([[1],[2],[3],[4],[5],[6]]) 
print(b) 

NameError: name 'np' is not defined

In [6]:
c = a * b 
print(c) 

NameError: name 'a' is not defined

In [36]:
d = b * a 
print(d)

[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]


In [2]:
'123'+'465'

'123465'

In [3]:
print(1+2+3)

6
